server:
  port: 8002
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mooc02?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
feign:
  hystrix:
    enabled: true

---
spring:
  profiles: dev

my-name:
  is: dev

---
spring:
  profiles: test
my-name:
  is: test  
